### ISSUE TITLE
Lulua hamza in klavaro 

### ISSUE THREAD

**Issue by Nasa00** [PromyLOPh/lulua#15]
i genuinely love this layout and consider to use it for daily use. hence, i try to learn touch typing with it in past month. 
then  i've encounter problem with أ إ ىٔ ىٕ  all the  ٔ and  ٕ addition doesn't showing in the klavaro practice programs.
furthermore i try online typing lesson such monkeytype.com or tybaa.com but the problem keep occurring. every  hurf with  ٔ addition keep identified as wrong words, 
is there any solution for this?

**Comment by PromyLOPh** [comment]
⁧شكراً جزيلاً!

Yes, this is a known problem, see #13 for a very technical explanation. The short version is that أ is two keystrokes with lulua, but only one for common layouts. Most typing tutors support only the latter and thus fail for lulua.

For monkeytype.com the solution in https://github.com/Miodec/monkeytype/issues/1403 (i.e. https://seerlite.github.io/monkeytype/issue/531-input-rewrite/) works for me. It’ll show the ي as incorrect first, but combined with ٔ  it’ll be displayed as correct. I hope that helps.

**Comment by Nasa00** [comment]
Thanks a lot,  i've tried it and it work flawlessly. Btw, recently i've been telling my friends about this amazing layout. Some of which, take same interest as i do. I hope this layout get a much more attention in the arab worlds, the standard 101 layout my windows have, just doesn't fit right for me (i find it weird and uncomfortable), then i accidentally found this layout and immediately fell in love with it. Once again thanks 👍

**Comment by PromyLOPh** [comment]
⁧ممتاز!

Would you be interested in helping to translate the website (or parts of it) to Arabic (الفصحى)? (#1) My Arabic is not good enough to translate all the technical terms 
للأسف.
